ci: fix test-prev-commits: checkout -; no coverage; improve msg
 - checkout previous commit, so the coverage upload uses the current
   code
 - do not run coverage reports when testing previous commits
 - improve failure message: display subject/author/name for each commit

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -201,13 +201,18 @@ script:
         echo "Testing commit $commit"
         git checkout "$commit"
         git --no-pager show --stat
-        if ! make all check; then
+        if ! DO_COVERAGE=0 make all check; then
           failed="$failed $commit"
         fi
         travis_fold_end
       done
+
+      git checkout -qf FETCH_HEAD
       if [ -n "$failed" ]; then
-        echo "Checks failed for these commits:$failed"
+        echo "Checks failed for these commits:"
+        for c in $commits; do
+          git log -1 --pretty="%h %s (%an, %ad)" "$c"
+        done
         false
       fi
     fi
