awesome-client: forward D-Bus error from dbus-send
If awesome does not respond to the D-Bus message, e.g. because it is not
running (yet), awesome-client now returns with a non-zero return code.

This can be used to check if awesome has finished starting up, which is
meant to be used for the functional test runner.

diff --git a/utils/awesome-client b/utils/awesome-client
--- a/utils/awesome-client
+++ b/utils/awesome-client
@@ -43,8 +43,14 @@ DBUS_METHOD=${DBUS_DEST}.Remote.Eval
 
 a_dbus_send()
 {
-    $DBUS_SEND --dest=$DBUS_DEST --type=method_call --print-reply $DBUS_PATH \
-        $DBUS_METHOD string:"$1" | tail -n +2
+    reply=$($DBUS_SEND --dest=$DBUS_DEST --type=method_call --print-reply \
+        $DBUS_PATH $DBUS_METHOD string:"$1")
+    ret=$?
+    if [ "$ret" != 0 ]; then
+        echo "E: $DBUS_SEND failed." >&2
+        exit $ret
+    fi
+    echo "$reply" | tail -n +2
 }
 
 if [ "$ISATTY" = 0 ]
